spring:
  application:
    name: LoginApi
  main:
    log-startup-info: true
    lazy-initialization: false
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: dev
    #active: test
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/loginapi
    username: postgres
    password: bgr.1907
    driver-class-name: org.postgresql.Driver
    connectionProperties: useUnicode=true;characterEncoding=utf-8
    hikari:
      maximum-pool-size: 15
      leak-detection-threshold: 20000
      auto-commit: true
      minimum-idle: 8
      max-lifetime: 60000
      idle-timeout: 20000
    dbcp2:
      test-while-idle: true
      test-on-borrow: true
      test-on-create: true
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        generate_statistics: false
        default_schema: public
        format_sql: true
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults=false:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-date-timestamps-as-nanoseconds: false
      write-dates-as-timestamps: false
      indent_output: true
    deserialization:
      fail-on-unknown-properties: false
    date-format: "yyyy.MM.dd HH:mm:ss"
  batch:
    job:
      enabled: false

server:
  servlet:
    context-path: /
  port: 8080